spring:
  application.name: Eureka
#  cloud.config.import-check.enabled: false

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

server.port: 8761

eureka.client:
  fetchRegistry: false
  registerWithEureka: false

