spring.application.name: core

mail.credentials:
  authMethod: basic
  username: user
  password: qwerty

server.port: 8081

eureka.client:
  initial-instance-info-replication-interval-seconds: 2
  instance-info-replication-interval-seconds: 1
  registry-fetch-interval-seconds: 1
